### ISSUE TITLE
double brackets {{}}

### ISSUE THREAD

**Issue by boyang9602** [mkllnk/gedit-rails-extensions#3]
Hi, I use angular so I need to use {{}} in haml, however, the language package doesn't contain this grammar and hints error.
Would you like to support this feature or how could I add this new feature myself?

**Comment by mkllnk** [comment]
I see that as a bug since angular should be seen as simple text. A pull request fixing this would be great. You probably need to look at `language-specs/haml.lang`.

**Comment by boyang9602** [comment]
oh.. I just removed the brackets check in haml.lang and the error will never show up. Easiest way for me.

**Comment by mkllnk** [comment]
Can you open a pull request with your modification?

**Comment by boyang9602** [comment]
Sure, I pulled request just now.

**Comment by mkllnk** [comment]
Merged https://github.com/mkllnk/gedit-rails-extensions/pull/4.
